<a href="https://colab.research.google.com/github/edmenciab733/ecc_qiskit_fallfest/blob/main/operaciones_cuanticas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

# Bases Computacional , Base Hadamard, y Base  Y

---

**Base computacional**

- $ |0\rangle $
- $ |1\rangle $

**Operador de Hadamard y transformación a la Base Hadamard**

El operador de Hadamard es una operación unitaria que actúa sobre un único qubit y tiene una variedad de aplicaciones importantes, desde la creación de superposiciones hasta la implementación de algoritmos cuánticos.


- $ H = \frac{1}{\sqrt{2}}\begin{pmatrix} 1 & 1 \\ 1 & -1 \end{pmatrix} $  


- $ |+\rangle $ = $H  |0\rangle $ = $ \frac{|0\rangle + |1\rangle}{\sqrt{2}} $


- $ |-\rangle $= $H  |1\rangle $ = $ \frac{|0\rangle - |1\rangle}{\sqrt{2}} $

**Base Y **

- $ |i\rangle $
- $ |-i\rangle $

## Matrices

In [19]:
ket_0 = np.array([[1], [0]])
ket_1 = np.array([[0], [1]])

In [20]:
H = 1/np.sqrt(2) * np.array([[1, 1], [1, -1]])

In [21]:
ket_p  = H.dot(ket_0)

In [22]:
ket_m = H.dot(ket_1)

In [23]:
ket_ip =  1/np.sqrt(2) * np.array([[1], [1j]])

In [24]:
ket_im = 1/np.sqrt(2) * np.array([[1], [-1j]])

# Relaciones entre qubits

Las relaciones entre qubits se realizan por medio kronecker

$|00\rangle = |0\rangle \otimes |0\rangle $

$  |01\rangle = |0\rangle \otimes |1\rangle $

$|10\rangle = |1\rangle \otimes |0\rangle $

$|11\rangle = |1\rangle \otimes|1\rangle $




In [25]:
ket_00 = np.kron(ket_0, ket_0)
ket_01 = np.kron(ket_0, ket_1)
ket_10 = np.kron(ket_1, ket_0)
ket_11 = np.kron(ket_1, ket_1)

# Operadores(Puertas) de Pauli, combinaciones y operaciones sobre 1 qubit

Los operadores de Pauli constituyen una serie de matrices que tiene efecto sobre qubits individuales.

La puerta $ X $ es análoga al bit clasico actua sobre el eje $ x $ y su efecto es rotar el eje mencionado un valor $ \pi $

In [26]:
X = np.array([[0,1], [1, 0]])

In [27]:
Z = np.array([[1,0], [0, -1]])

In [28]:
Y = np.array([[0, -1j], [1j, 0]])

In [29]:
I = np.array([[1,0], [0,1]])

Para combinar dos o n operadores cuanticos que terminaran a afectando a 2 o $ n $ qubits tambien se realiza el producto de kronecker entre los operados por ejemplo para dos puertas $ XX $ sería:

$ XX = X \otimes X $

El <a href="https://repositoriodigital.uns.edu.ar/handle/123456789/5841#:~:text=El%20producto%20de%20Kronecker%20se,el%20c%C3%A1lculo%20de%20valores%20singulares." > producto de kronocker </a>garantiza que los qubits se mantengan independiente. No es una operación sobre dos qubits

In [30]:
XX = np.kron(X, X)
XX

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

Ejemplo si queres afectar a aplicar al par de de qubits  $|00\rangle$ con la puerta $ X$ aplicado a ambos qubits. La operación es cuanto sigue:

$ XX |00\rangle $


In [31]:
np.dot(XX, ket_00)

array([[0],
       [0],
       [0],
       [1]])

En la notación de bra-ket, comúnmente utilizada en mecánica cuántica, el producto tensorial de operadores lineales se puede definir de la siguiente manera. Consideremos dos espacios vectoriales, $V$ y $U$ con vectores $ |v\rangle $ en $V$ y $ |u\rangle $ en $U$. El producto tensorial de los operadores  $ A y  B $ denotado por $ A \otimes B $ actúa sobre el espacio producto tensorial de $ U \otimes V $ por tanto se puede decir que tambien actua sobre $ u$  y $ v $






$ (A \otimes B ) ( |v\rangle \otimes |u\rangle ) =  (A \otimes |v\rangle ) (B \otimes |u\rangle)$

Ejemplo

$ ZX|10\rangle = Z|1\rangle X|0\rangle $

In [32]:
ZX = np.kron(Z, X)
ket1ket0 = np.kron(ket_1, ket_0)
ZXket1ket0 = ZX.dot(ket1ket0)
ZXket1ket0

array([[ 0],
       [ 0],
       [ 0],
       [-1]])

In [33]:
Zket1 = Z.dot(ket_1)
Xket0 = X.dot(ket_0)
Zket1Xket0 = np.kron(Zket1,Xket0 )
Zket1Xket0

array([[ 0],
       [ 0],
       [ 0],
       [-1]])